name: day_task
description: Daily tasks managment application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  easy_localization: ^3.0.2
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_facebook_auth: ^6.0.1
  flutter_form_builder: ^9.1.0
  flutter_svg: ^2.0.7
  form_builder_validators: ^9.0.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  mockito: ^5.4.2
  url_launcher: ^6.1.12
  firebase_auth_mocks: ^0.12.0
  percent_indicator: ^4.2.3
  network_image_mock: ^2.1.1
  firebase_database: ^10.2.5
  cloud_firestore: ^4.9.1
  fake_cloud_firestore: ^2.4.1+1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/translations/
