// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYyUK_zTL0Yus8MJkiWjhLR2xWYmw9FFM',
    appId: '1:1020119625756:web:e11c5b5bb30cb13404afd9',
    messagingSenderId: '1020119625756',
    projectId: 'daytask-1c41f',
    authDomain: 'daytask-1c41f.firebaseapp.com',
    storageBucket: 'daytask-1c41f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY37HuJeB1s44YjYMrWcIQ5UFgnCTjKl8',
    appId: '1:1020119625756:android:b1b4ccf32d3f445b04afd9',
    messagingSenderId: '1020119625756',
    projectId: 'daytask-1c41f',
    storageBucket: 'daytask-1c41f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqLBA4c1dJeYXZFrWxoOTkATTt9DaKRI',
    appId: '1:1020119625756:ios:459087956e52e07a04afd9',
    messagingSenderId: '1020119625756',
    projectId: 'daytask-1c41f',
    storageBucket: 'daytask-1c41f.appspot.com',
    iosClientId:
        '1020119625756-pkdt59qlmp289t1vtqamkr7nvss41f84.apps.googleusercontent.com',
    iosBundleId: 'com.aberardi.dayTask',
  );
}
